# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
title: Lee1's Journey
description: Lee的随想和技术空间

defaults:
    values:
      title: Lee2's Journey
      description: Lee2的随想和技术空间


author:
  name: lee
  email: penglee87@163.com
  github: penglee87
  zhihu: https://www.zhihu.com/people/lee-82-75-31/activities

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


BASE_PATH:

gems:
  - jekyll-paginate
